# Generated by Django 3.2.5 on 2021-07-24 09:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.CharField(max_length=128),
        ),
    ]
