# Generated by Django 3.2.5 on 2021-07-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery', '0004_alter_grocery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
