# Generated by Django 3.2.5 on 2021-07-24 15:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery', '0005_alter_grocery_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='status',
            field=models.IntegerField(default=2),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
        ),
    ]
